### ISSUE TITLE
Ability targeting

### ISSUE THREAD

**Issue by 628426** [timothypratley/pirates#5]
Some abilities like Mutiny require targets as written. Does the game have targets, like with tab key, or should abilities be tweaked

**Comment by timothypratley** [comment]
Check with the game designers. I think target selection will be a necessary feature. But if we can prioritize and design non-targeting abilities first, that could allow us to defer it.

**Comment by 628426** [comment]
https://github.com/timothypratley/pirates/wiki/Combat#target
